/**
 * Copyright [2014] Gaurav Gupta
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package org.netbeans.jbatch.modeler.specification.model.job;

import org.netbeans.jbatch.modeler.spec.Job;
import org.netbeans.jbatch.modeler.spec.Listeners;
import org.netbeans.jbatch.modeler.spec.Properties;
import org.netbeans.jbatch.modeler.spec.core.Definitions;
import org.netbeans.jbatch.modeler.spec.design.BatchDiagram;
import org.netbeans.jbatch.modeler.spec.design.BatchPlane;
import org.netbeans.jbatch.modeler.specification.model.JavaBatchDiagramModel;
import org.netbeans.modeler.config.element.ElementConfigFactory;
import org.netbeans.modeler.core.ModelerFile;
import org.netbeans.modeler.core.NBModelerUtil;

public class JobDiagramModel extends JavaBatchDiagramModel {

    @Override
    public void init(ModelerFile modelerFile) {
        ElementConfigFactory elementConfigFactory = modelerFile.getVendorSpecification().getElementConfigFactory();
        Definitions definition = new Definitions();
        Job job = new Job();
        job.setListeners(new Listeners());
        job.setProperties(new Properties());
        elementConfigFactory.initializeObjectValue(definition);
        elementConfigFactory.initializeObjectValue(job);

        job.setId(NBModelerUtil.getAutoGeneratedStringId());
        job.setKey(job.getId());
        definition.setName(modelerFile.getName());

        definition.setJob(job);

        BatchDiagram diagram = new BatchDiagram();
//        diagram.setId(BPMNUtil.getAutoGeneratedStringId());
        BatchPlane plane = new BatchPlane();
        plane.setId(NBModelerUtil.getAutoGeneratedStringId() + "_p");
        diagram.setBatchPlane(plane);
        plane.setBatchElement(job.getId());
        definition.addBatchDiagram(diagram);

        this.setDiagramElement(diagram);
        this.setDefinitionElement(definition);
        this.setRootElement(job);

        this.getModelerScene().setRootElementSpec(job);
    }
}
